### ISSUE TITLE
Use `Data.Map.Lazy.valid`

### ISSUE THREAD

**Issue by phadej** [NorfairKing/validity#1]
There could be invalid structurally `Map k v`: http://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Map-Lazy.html#v:valid

---

related: parent packages should note that there are companion instance packages.

**Comment by NorfairKing** [comment]
> There could be invalid structurally Map k v: http://hackage.haskell.org/package/containers-0.5.7.1/docs/Data-Map-Lazy.html#v:valid

Yes!

I would need access to the internals of `Map` to implement `genUnchecked` of `GenValidity` but I can definitely use this `isValid` method.

> related: parent packages should note that there are companion instance packages.

Yes!
This is going on my todo list.
