### ISSUE TITLE
genvalidity-sydtest specs for Enum/Bounded

### ISSUE THREAD

**Issue by cumber** [NorfairKing/validity#110]
I've been working on a set of specs for testing manually-written `Enum` instances (`toEnum` and `fromEnum` round-trip, if the type is `Bounded` too then `pred`/`succ` fail only on `minBound`/`maxBound`, etc). I was going to write up a pull request when done.

Now I have rethought what I was doing a little so that I no longer have a use-case for an `Enum` instance that can't be auto-derived. So I don't really need specs for `Enum` instances any more. I'm happy to finish and submit the pull request, if you think it would be useful to have in `genvalidity-sydtest`. But given I don't have an immediate use case, I thought I'd check first whether it's something you would actually want to provide.

**Comment by NorfairKing** [comment]
@cumber any news?

**Comment by cumber** [comment]
@NorfairKing Ah, it *has* been a while hasn't it? :( Rather a lot of life has been happening.

I'm still aiming to finish this off and shoot a pull request. Not likely to be in the next few weeks or anything though; I don't mind if you want to tidy up this issue, it doesn't need to be sitting open.

**Comment by NorfairKing** [comment]
@cumber okido, pr welcome!
