### ISSUE TITLE
Validity is wrong for rational numbers

### ISSUE THREAD

**Issue by eschnett** [NorfairKing/validity#14]
The code that checks whether `Rational` is valid looks like this:
```
    isValid (d :% n) = isValid n && isValid d && d > 0
```
This confuses numerator and denominator, and checks whether the numerator is positive:
```
import Data.Validity
isValid (0::Rational)
False
```

**Comment by NorfairKing** [comment]
Oh dear, that's quite silly! A PR is certainly welcome!

**Comment by eschnett** [comment]
This has been corrected.
