### ISSUE TITLE
Check validity for Functor instances?

### ISSUE THREAD

**Issue by eschnett** [NorfairKing/validity#19]
If I define my own instance of `Functor`, is there a convenient way to have `validity` check that it satisfies the functor laws? I could cobble something together, but my question is:
- Are the functor laws already described in `validity`? I couldn't find them.
- If now, how would I best generically define the laws?
- How would I apply this then to my own `Functor` instance?

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/validity/blob/master/genvalidity-hspec/src/Test/Validity/Functor.hs

There you go!

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/validity/blob/master/genvalidity-hspec/src/Test/Validity/Functor.hs#L53-L57

**Comment by NorfairKing** [comment]
It may be that these are not general enough, in which case you can feel free to split out the laws into seperate test combinators and submit a PR :)

**Comment by NorfairKing** [comment]
Closing this. Feel free to re-open if you would like more help/answers.

**Comment by eschnett** [comment]
Thanks for the reply. I looked at the code last week, and it seems to do what I need. However, I didn't have the time yet to try it out.
