### ISSUE TITLE
Missing documentation at http://hackage.haskell.org/package/validity

### ISSUE THREAD

**Issue by sjakobi** [NorfairKing/validity#2]
I can't tell what this package is about from looking at the above Hackage page (nor from looking at the README in this repo).

It would be great if you could add some info to the description field in the .cabal file(s) and make sure that the haddocks is generated or upload it yourself. I believe the neil tool can do the latter for you.

You could also consider adding validity to stackage, where the haddocks are generated more reliably.

**Comment by NorfairKing** [comment]
Hi.

You bring up a very good point.
Currently most of the documentation is in the `Data.Validity` module:
http://hackage.haskell.org/package/validity-0.3.0.3/docs/Data-Validity.html

I would like to add some more documentation in the README and in the description.
The reasons I haven't done it yet are 1. Time constrainss and 2. Writing the same documentation in three places is a very boring job.

As for adding `validity` and compagnons to stackage: Sounds good to me.

Adding this to my todo list.

**Comment by sjakobi** [comment]
Yes, writing and maintaining docs can be quite the chore.

To minimize redundancy I suggest you give a short overview of the packages and maybe a worked example that showcases some of them in the README, and distribute that README together with all the packages. Sadly, one apparently cannot include files like `../README.md` in the `extra-source-files` section so you'd have to copy the README into the package directories during release.

Then you could simply refererence the README and the module documentation from the `description` field so people will know where to look.

**Comment by NorfairKing** [comment]
I added some docs, any feedback would be very helpful!

**Comment by sjakobi** [comment]
Looks great overall!

Not sure "Validity and validity-based testing" is a good summary/slogan though. I think "invariant" might be a word that more people will have an intuition for. How about something like "Utilities for encoding and testing invariants"

Also, I wondered which modules I'd have to import to run the examples, e.g. I didn't know where `forAll` was defined.

**Comment by NorfairKing** [comment]
Thanks for the feedback!

In general I think people using this will know that `forAll` comes from `QuickCheck`.
