### ISSUE TITLE
GenUnchecked shouldn't be required for GenValid

### ISSUE THREAD

**Issue by Nickske666** [NorfairKing/validity#22]
Right now, a type needs to be an instance of GenUnchecked in order to be made an instance of GenValid.
I think this might be unnecessary. Abstractly speaking, I don't think it needs to be, and it might be more elegant if the code reflected this.

**Comment by NorfairKing** [comment]
At the moment this is necessary because the default implementation of `genValid` is ``genUnchecked `suchThat` isValid``. Feel free to figure out how to get out of that and make a new issue.
