### ISSUE TITLE
Generate validity

### ISSUE THREAD

**Issue by Nickske666** [NorfairKing/validity#23]
Upon defining a type to be an instance of validity by defining an isValid function,
the validate function is automatically generated. However, this function does not always
actually compile. I would propose to try and find a good default implementation, as you
are right now, but if this implementation doesn't work, to use ```validate = validateByCheckingName [name of the type]```.

**Comment by NorfairKing** [comment]
> However, this function does not always actually compile.

That's not entirely accurate. Look into the generic programming we use.

You do bring up a good point: We should move `isValid` out of the `Validity` type class. A type class would be welcome.

**Comment by NorfairKing** [comment]
Done
