### ISSUE TITLE
Deriving useful implementation for genValid

### ISSUE THREAD

**Issue by CSVdB** [NorfairKing/validity#39]
In practise, the Generics-based default genValid instance is often too slow.
This means genValid often needs to be implemented by hand.
However, many composite data types have a validity instance saying
"MyType is valid iff its fields are valid". Because of the ubiquity of this pattern,
I propose to implement a Generics-based implementation (just like was done for
genUnchecked, but without making it the defaults implementation).

**Comment by NorfairKing** [comment]
Sounds great, I'm not sure what we should call it yet, but a PR is welcome.

**Comment by NorfairKing** [comment]
Marking this as solved then!
