### ISSUE TITLE
genvalidity-hspec-0.3.0.0 uses TypeApplications which was introduced only in GHC-8.0

### ISSUE THREAD

**Issue by sjakobi** [NorfairKing/validity#4]
Please make a revision that adds a lower bound on base.

If possible I'd propose removing the use of that extension so the package can be used with older versions of base.

**Comment by sjakobi** [comment]
Please also make a revision of v0.3.1.0

**Comment by NorfairKing** [comment]
> Please make a revision that adds a lower bound on base.

Yes

> If possible I'd propose removing the use of that extension so the package can be used with older versions of base.

No. TypeApplications is central to the ui of genvalidity-hspec.

> Please also make a revision of v0.3.1.0

Okay!

**Comment by sjakobi** [comment]
> No. TypeApplications is central to the ui of genvalidity-hspec.

Ah, I didn't know that. For path that means of course that the validity-test testsuite can only be run with `base >= 4.9` as long as it uses `Test.Validity`. That makes it a bit less useful for checking backwards compatibility with dependencies.

**Comment by NorfairKing** [comment]
> That makes it a bit less useful for checking backwards compatibility with dependencies.

I agree, but it's still better than not running the validity tests at all.

**Comment by sjakobi** [comment]
Right. Maybe you'd like to provide an alternative, more widely compatible UI that can be used with `Proxy` for example? It's not a pressing issue for `path` though IMO.

**Comment by NorfairKing** [comment]
I don't think I should go out of my way to add more complexity just for the sake of backward compatibility, but if anyone wants to take the time to make PR with code like this, I'd still consider it.

**Comment by sjakobi** [comment]
Sounds reasonable.

**Comment by NorfairKing** [comment]
Actually, the idea in #80 sounds better to me that to provide a parallel API.

**Comment by NorfairKing** [comment]
The latest releases should allow you to use everything that used to be available in `genvalidity-hspec` that doesn't use `TypeApplications`, because these functions are now in `genvalidity-property`.
