### ISSUE TITLE
README: empty prime factorisation

### ISSUE THREAD

**Issue by amigalemming** [NorfairKing/validity#49]
The README claims that only numbers greater than one have a prime factorisation and that the prime factorisation is always a non-empty list. I'd say that `1` has a perfect prime factorisation, namely the empty list. It holds `product [] == 1`.

**Comment by NorfairKing** [comment]
Oh dear. Why do I always try to use mathematics examples. It invariably leads to someone pointing out that my example is wrong.

You're right of course, and I'd be happy to have it fixed with a PR.

**Comment by amigalemming** [comment]
On Thu, 30 Aug 2018, Tom Sydney Kerckhove wrote:

> Oh dear. Why do I always try to use mathematics examples. It invariably 
> leads to someone pointing out that my example is wrong.
> 
> You're right of course, and I'd be happy to have it fixed with a PR.

I am afraid it kills your example, doesn't it?

Maybe "maximum" is a better example because it really requires a non-empty 
list as input.

**Comment by NorfairKing** [comment]
> I am afraid it kills your example, doesn't it?

Not per-se. Now it becomes `GreaterThanZero` and one of the invariants of the `PrimeFactorisation` dissappears (`not . null`).

**Comment by NorfairKing** [comment]
This should be fixed now.
