### ISSUE TITLE
Missing function isValidValidation

### ISSUE THREAD

**Issue by np** [NorfairKing/validity#53]
This library is working great so far me apart for a minor catch.
I can't find a way to go from a `Validation` to a `Bool`.
I know that most of the time this is not needed as we can use `isValid`.
However in my case I have other functions producing a `Validation` than `validate`.
Example:

```
composable :: T -> T -> Validation
```

**Comment by NorfairKing** [comment]
@np I'd be happy with this contribution. In general, I'd like more functions that deal with `Validation` values. For now, you can use `== mempty`. It does what you're looking for.
