### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by qrilka** [NorfairKing/validity#57]
genvalidity:genvalidity-test timed out on test machine for Stackage builds (the current test suite timeout is 10 minutes), the last lines were
```
  (Float,Float,Float,Float,Float)
    genUnchecked of (Float,Float,Float,Float,Float) does not crash while validating
      +++ OK, passed 100 tests.
    shrinkUnchecked of (Float,Float,Float,Float,Float) only produces values that do not crash while validating
      +++ OK, passed 20 tests.
    shrinkUnchecked of (Float,Float,Float,Float,Float) does not shrink to itself
      +++ OK, passed 20 tests.
    genValid of (Float,Float,Float,Float,Float) generates only valid values
      +++ OK, passed 100 tests.
    shrinkValid of (Float,Float,Float,Float,Float) shrinks to only valid values
      +++ OK, passed 20 tests.
```
And on my machine 3rd run took
```
genvalidity-0.7.0.0: Test suite genvalidity-test passed

real	16m19,237s
user	25m46,936s
sys	17m34,115s
```
and it looked like the most problematic tests were for Float and Double tuples.

I will add this package into `expected-test-failures` section in build constraints of Stackage.

**Comment by NorfairKing** [comment]
It could be that `QuickCheck` changed something about the way shrinking floats works again. I'll look into it.

**Comment by NorfairKing** [comment]
These are possible reasons:

https://github.com/nick8325/quickcheck/commit/75db4d2586ab23b674b2e2262d0798917959bc9d
https://github.com/nick8325/quickcheck/commit/8e0434b75c3ca78952fd5740fb3154ff66b69809
https://github.com/nick8325/quickcheck/commit/bd4e5533b4917a69da84f0c3583359b25c75778a

**Comment by NorfairKing** [comment]
@qrilka I think I fixed it in f4882ec. Could you check?

**Comment by qrilka** [comment]
Yeah, looks much better, the slowest run was below 4s, will you do a minor release maybe?

**Comment by NorfairKing** [comment]
Just uploaded `genvalidity-0.7.0.1`.
