### ISSUE TITLE
Validity for ShortByteString

### ISSUE THREAD

**Issue by lehins** [NorfairKing/validity#58]
There is currently no instance for [`ShortByteString`](https://www.stackage.org/haddock/lts-13.9/bytestring-0.10.8.2/Data-ByteString-Short.html#t:ShortByteString) in `validity-bytestring`.

**Comment by NorfairKing** [comment]
That's only because I've never needed it. PR welcome!

**Comment by NorfairKing** [comment]
This has now been merged into `development` and will be on `master` and released soon.

**Comment by NorfairKing** [comment]
This is fixed in the latest release
