### ISSUE TITLE
GenUnchecked instance for strict ByteString is utterly bad

### ISSUE THREAD

**Issue by lehins** [NorfairKing/validity#59]
As the documentation states:
```
-- | WARNING: Unchecked ByteStrings are *seriously* broken.
-- The pointer may still point to something which is fine, but
-- the offset and length will most likely be complete nonsense.
-- This will most-likely lead to segfaults.
```
It does indeed lead to consistent segfaults, as such should either be removed or fixed. Even something like that would be better than what there is now: `genUnchecked = SB.pack <$> genUnchecked`

**Comment by NorfairKing** [comment]
This is broken as intended. The semantics of `GenUnchecked` mean that any possible value should be generatable. If you want nice `ByteString`s, use `GenValid`.

**Comment by NorfairKing** [comment]
This is now being fixed, see the `docs/BYTESTRING.md` file.
In the near future, there won't be a `GenUnchecked ByteString` instance anymore.

**Comment by NorfairKing** [comment]
This is fixed in the latest release
