### ISSUE TITLE
genvalidity-hspec-optics is named confusingly

### ISSUE THREAD

**Issue by phadej** [NorfairKing/validity#70]
It's about `lens` not `optics`!

**Comment by NorfairKing** [comment]
This is from before the optics library existed, and it only contains tests for lenses because i haven't needed the other things in the lens library.

**Comment by phadej** [comment]
(technically work on `optics` was announced in 2017, but let's not argue who was first).

Currently, `genvalidity-hspec-optics` description says

> Standard spec's for optics

And in current state of affairs, this is misleading.

**Comment by NorfairKing** [comment]
Sure, I don't know if there's a way to rename a package on hackage...
