### ISSUE TITLE
Commutative properties type

### ISSUE THREAD

**Issue by grepcake** [NorfairKing/validity#81]
Is there a reason for `commutative` property to take only functions that have the same result type as its arguments? 

That is, 
`commutativeOnGens :: (Show a, Eq a) => (a -> a -> a) -> Gen (a, a) -> ((a, a) -> [(a, a)]) -> Property`
 instead of 
`commutativeOnGens :: (Show a, Eq b, Show b) => (a -> a -> b) -> Gen (a, a) -> ((a, a) -> [(a, a)]) -> Property`.

**Comment by NorfairKing** [comment]
No reason, feel free to fix that!

**Comment by NorfairKing** [comment]
Should be fixed now, thanks @grepcake for the quick work!
