### ISSUE TITLE
GenUnchecked and abstract data types

### ISSUE THREAD

**Issue by seagreen** [NorfairKing/validity#86]
I really like the `GenUncheck` vs `GenValid` distinction. However I'm running into an issue using it in practice. Pretty much all of the meaningful types in my programs are composed of at least one abstract data type-- usually `Text`, but sometimes others. This causes a problem because I lose the usefulness of the `GenUnchecked` vs. `GenValid` distinction.

Eg: imagine I'm implementing a programming language. I'd like `GenUnchecked` to generate all possible ADTs so that I can assert they can all roundtrip through serialization-parsing, etc. Then I'd like `GenValid` to generate only ones that typecheck, so that I can assert things like they give the same results when run through different interpreters. However, since I usually have `Text` in there somewhere I can't do this, because `GenUnchecked` is forbidden for `Text`.

Does that make sense? If it does I think the problem comes from different users having different perspectives on things like `Text`. An implementer of the `text` package would like a `GenUnchecked` instance for `Text` that truly generates all possible instances of [the internal data type](https://hackage.haskell.org/package/text-1.2.4.0/docs/src/Data.Text.Internal.html#Text).

However, a user of the `text` package likely wants to be able to trust the abstraction and that the smart constructors like `pack` are implemented correctly, and have `GenUnchecked` for `Text` generate only what could be generated with `pack`.

What are your thoughts on this? I think a `GenUnchecked Text` instance that generates valid `Text` is what almost all users are going to want from `genvalidity-text`, but I'm curious to hear the reasoning behind the current setup.

**Comment by NorfairKing** [comment]
Hi @seagreen! Thanks for the thoughtful questions.

There's a lot to unpack here.
First of all, I'd like to make sure that it's clear why the distinction between `GenUnchecked` and `GenValid` exists.
Generating a generator (not a typo) for any type is an open area of research. See [this paper](https://arxiv.org/abs/1607.05443).
However, it is possible to generate the implementation of `GenUnchecked` using `Generic`.
By adding the `Validity` constraint, we can also generate the implementation of `GenValid`.

In order for that generation to work the way it's supposed to, `GenUnchecked` and `GenValid` need to have the following semantics:
- `GenUnchecked` _MUST_ generate every possible value that can exist at runtime.
- `Validity` _MUST_ specify every invariant that must be maintained at runtime. That means that an `invalid` value _MUST NOT_ exist at runtime.
- `GenValid` _MUST_ generate every possible value that would satisfy the `isValid` predicate.

Does that make sense so far?


To get back to your situation, I think this is the issue:  

> I'd like GenUnchecked to generate all possible ADTs

If you have `Text` values in your ADTs, then that means that you'll generate values that can only do one thing: segfault.
I claim that this is not going to be useful.

However, you can still use validity in the following principled way:
Have one `ParsedButNotTypedCheckedADT` type and one `TypeCheckedADT`. The former will have validity constraints that involve their `Text`s being valid. The latter will have additional validity constraints about their being type-checked.

> What are your thoughts on this? I think a GenUnchecked Text instance that generates valid Text is what almost all users are going to want from genvalidity-text, but I'm curious to hear the reasoning behind the current setup.

You may be right, but the whole library would fall apart if we do this. A `Text` value is not trivially valid, and we cannot pretend it is.
I have found plenty of bugs in the Haskell library ecosystem by writing this library, that would have been hidden by optimistic/naive `GenUnchecked` instances.

You can read more about this here: https://github.com/NorfairKing/validity/blob/master/docs/BYTESTRING.md


P.S. When it comes to generating implementations of `GenValid`, you can still use `genValidStructurally` if you are using `Text` somewhere.

**Comment by seagreen** [comment]
Hey @NorfairKing, thanks for the great response.

> A `Text` value is not trivially valid, and we cannot pretend it is.
> I have found plenty of bugs in the Haskell library ecosystem by writing this library, that would have been hidden by optimistic/naive `GenUnchecked` instances.

Are you talking about finding bugs in core libraries like `text`, or bugs because people were using the unsafe functions from libraries like `text` in an incorrect way? If the former, yikes!

Also, a general thought: I think working on libraries (especially core ones like `text` and `bytestring`) is going to have such different needs from doing application development that perhaps they need different testing strategies. But I'll keep describing my application developer's perspective, in case there is a way to find synthesis.

> > I'd like GenUnchecked to generate all possible ADTs
>
> If you have `Text` values in your ADTs, then that means that you'll generate values that can only do one thing: segfault.
I claim that this is not going to be useful.

Whoops, I think I made a *double* mistake here. I meant algebraic type not ADTs, and I also left off an essential clarification. I'll just start over:

*When implementing a programming language expression type, I'd like `GenUnchecked` to generate all possible algebraic types that can be created through the smart constructors for any abstract data types I'm using.*

That way I can use `GenUnchecked` to test serialization/deserialization, `GenValid` for typechecking, etc.

Perhaps the typeclasses I actually want aren't `GenUnchecked` and `GenValid`. But one way or another I'd like two typeclasses: one that generates all values of my type with the important caveat that smart constructor-enforced variants hold, and another that filters the above by some `isValid` function.

> However, you can still use validity in the following principled way:
> Have one `ParsedButNotTypedCheckedADT` type and one `TypeCheckedADT`.

This is a good point. The problem is that there are so many things that require new data types (eg the advice to keep database types separate from business logic, API types separate from business logic, etc), that it's already easy to get bogged down in type number of separate types for things that are basically the same.

**Comment by NorfairKing** [comment]
> Are you talking about finding bugs in core libraries like text, or bugs because people were using the unsafe functions from libraries like text in an incorrect way? If the former, yikes!
 
 Both :D
 
 I think I understand your idea. I don't think my response would be any different this time, but let me elaborate a bit.
 
 This is the way I'd start to go about what you're trying to do:
 
 ```
 parse :: Text -> Either ParseError ParsedAST
 typeCheck :: ParsedAST -> Either TypeError TypeCheckedAST
 ```
 
 To get the instances that you want, you use `genValid` for each (which is what you want).
 This is how you would define them (no code omitted)
 ```
import Data.GenValidity
import Data.GenValidity.Text ()

instance GenValid ParsedAST where
  genValid = genValidStructurally
  shrinkValid  = shrinkValidStructurally 

instance GenValid TypeCheckedAST where
  genValid = genValidStructurally
  shrinkValid  = shrinkValidStructurally 
 ```
 
 The reason that you do things this way is the same reason that `GenInvalid` is pretty much useless.
 `GenInvalid` is pretty much useless because there are many reasons that any given value can be invalid. In your example a typechecked ast could be invalid for at least two reasons: the `Text` could be invalid or the types could be mismatched.
 
 I can also recommend that you consider some sort of phantom type parameter for your type-checked AST.

**Comment by NorfairKing** [comment]
> I'd like to be able to operate at a level of abstraction where I assume the smart constructors are implemented correctly.

You can use the smart contructors in your `genValid` instance and do this.
`Char` is also not trivially valid by the way, because it's a machine word underneath :D
