### ISSUE TITLE
Compile failure w/ genvalidity-path-0.1.0.1 & base-4.7

### ISSUE THREAD

**Issue by hvr** [NorfairKing/validity#9]
The cabal file states compatibility w/ base >= 4.7, however GHC 7.8.4 disagrees:

```
Configuring component lib from genvalidity-path-0.1.0.1...
Preprocessing library genvalidity-path-0.1.0.1...
[1 of 1] Compiling Data.GenValidity.Path ( src/Data/GenValidity/Path.hs, /tmp/matrix-worker/1489783673/dist-newstyle/build/x86_64-linux/ghc-7.8.4/genvalidity-path-0.1.0.1/build/Data/GenValidity/Path.o )

src/Data/GenValidity/Path.hs:13:25:
    Not in scope: ‘<$>’
    Perhaps you meant ‘</>’ (imported from Path)
```

**Comment by NorfairKing** [comment]
My CI disagrees with you: https://travis-ci.org/NorfairKing/validity/jobs/212167555
Where's the discrepancy?

**Comment by NorfairKing** [comment]
Ah, found the problem. A moment please.

**Comment by hvr** [comment]
@NorfairKing Btw, Stack CI is not very good at discovering version bound issues since it relies on precomputed freeze files. Most specifically, Stackage snapshots for non-latest GHCs don't get updated so you simply don't test configurations you'd get when using `cabal`.

OTOH, (shameless plug alert), I've added experimental support for testing both, LTS snapshots and w/o LTS snapshots w/ cabal (you can see it in action here e.g.: https://travis-ci.org/hvr/cassava/builds/211281691) which avoids the pitfalls of Stack-based CI and reduces my workload as a Hackage Trustee having to fixup Hackage meta-data & contact package authors... :-)

**Comment by NorfairKing** [comment]
@hvr, Are there any docs on how to do CI correctly for Haskell?

**Comment by hvr** [comment]
@NorfairKing Unfortunately, I have to answer "not yet" to that :-/ I've got a couple of CI-related features in the pipeline which are not yet ready yet for general consumption, not the least because there's a few kinks that I need to get out of `cabal new-build` as well as some features in the matrix builder (see also http://104.239.175.197:8080/latest which is the latest prototype).

**Comment by NorfairKing** [comment]
This matrix builder looks very promising, but my gut says this matrix is too expensive to build in general.
Thank you for your help here.
I'm going to close this issue because it is solved in the new release, I think.
Maybe we should have an offline (email) conversation about how I could help with maintainability of Haskell packages.
