### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by piq9117** [NorfairKing/validity#91]
I tried building `validity` with these steps

1. Going into a nix shell with `nix-shell`
2. `cd validity`
3. `stack build`

I then get this https://gist.github.com/piq9117/ca163f79352bcb171ce6ae537208cf44

I apologize if there is already docs on how to do this but I've looked in `docs/` and couldn't find anything. I can update the docs if I learn how to build this project.

**Comment by NorfairKing** [comment]
Hi @piq9117 !
You don't need to `cd validity` (in fact it doesn't help, you'll still build everything with `stack build`.)
You'll want to use `stack build validity` instead.

Also; `ExitFailure (-11)` is out-of-memory, I think? So maybe try `stack build validity --jobs 1`?

**Comment by piq9117** [comment]
Thanks @NorfairKing !
