### ISSUE TITLE
Aeson tests should support golden round trip tests

### ISSUE THREAD

**Issue by dustin** [NorfairKing/validity#94]
I'd like something similar to [hspec-golden-aeson](https://hackage.haskell.org/package/hspec-golden-aeson-0.9.0.0/docs/Test-Aeson-GenericSpecs.html#v:roundtripAndGoldenSpecs) allowing `GenValidity` to create a sufficient consistent set of values that can be serialized and tested against in a golden test.

Right now, one must think of all of the ways to build an object (including transitive values) and write tests for all the combinations.  It'd be great to do this automatically.

**Comment by NorfairKing** [comment]
We can do this, but you're not going to like the result.
Arbitrary data is not what you want to be using in this case, you want fake data instead.

**Comment by dustin** [comment]
Understood.  I've used `hspec-golden-aeson` and the output is not super pleasant.  It's not a replacement for having known hand-written bits, but it's better than trying to imagine all possibilities and having embedded objects change unexpectedly.

**Comment by NorfairKing** [comment]
You might want to make a similar issue in the fake-data repo instead.

**Comment by NorfairKing** [comment]
`sydtest-aeson` does what you want, I think.
